name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ci:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'  # Соответствует требованию NodeJS >= 18
        cache: 'npm'        # Кэширование npm зависимостей

    - name: Install dependencies (make setup)
      run: make setup

    - name: Run tests (make test)
      run: make test

    - name: Run linter (make lint)
      run: make lint